{% set name = "arn" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/instacart/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b2d7de92c90649db806a44ffcc2d9a096891d3248ccfcdee9e695a49304725e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7  # Package is available from 3.6, see https://github.com/instacart/arn/issues/11
  run:
    - python >=3.7

test:
  imports:
    - arn
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/instacart/arn
  license: BSD-3-Clause-Clear
  license_family: BSD
  license_file: LICENSE
  summary: A Python library for parsing AWS ARNs.
  doc_url: https://arn.readthedocs.io/en/latest/
  dev_url: https://github.com/instacart/arn

extra:
  recipe-maintainers:
    - BastianZim
